apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trakrf-ingester.fullname" . }}
  labels:
    {{- include "trakrf-ingester.labels" . | nindent 4 }}
type: Opaque
stringData:
  MQTT_URL: {{ .Values.mqtt.url | quote }}
