{{- if and .Values.metrics.enabled .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "trakrf-ingester.fullname" . }}
  labels:
    {{- include "trakrf-ingester.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "trakrf-ingester.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
