apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: trakrf
  namespace: argocd
spec:
  description: TrakRF platform workloads
  sourceRepos:
    - "https://github.com/trakrf/infra.git"
    - "https://argoproj.github.io/argo-helm"
    - "https://prometheus-community.github.io/helm-charts"
    - "https://stackgres.io/downloads/stackgres-k8s/stackgres/helm/"
  destinations:
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: trakrf
    - server: https://kubernetes.default.svc
      namespace: monitoring
    - server: https://kubernetes.default.svc
      namespace: kube-system
    - server: https://kubernetes.default.svc
      namespace: stackgres
    - server: https://kubernetes.default.svc
      namespace: trakrf-db
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "*"
      kind: CustomResourceDefinition
    - group: "*"
      kind: ClusterRole
    - group: "*"
      kind: ClusterRoleBinding
    - group: "admissionregistration.k8s.io"
      kind: MutatingWebhookConfiguration
    - group: "admissionregistration.k8s.io"
      kind: ValidatingWebhookConfiguration
    - group: "apiextensions.k8s.io"
      kind: "*"
  namespaceResourceBlacklist:
    - group: ""
      kind: ResourceQuota
    - group: ""
      kind: LimitRange
