terraform {
  required_version = ">= 1.0.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  backend "s3" {
    # endpoints injected via backend.conf (generated by justfile from env vars)
    bucket = "tf-state"
    key    = "aws.tfstate"
    region = "auto"

    skip_credentials_validation = true
    skip_region_validation      = true
    skip_metadata_api_check     = true
    use_path_style              = true
  }
}

provider "aws" {
  region  = "us-east-1"
  profile = "default"
  # Explicitly use AWS CLI profile to avoid conflict with AWS_* env vars used for R2 backend
}
