apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trakrf-backend.fullname" . }}
  labels:
    {{- include "trakrf-backend.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
  RESEND_API_KEY: {{ .Values.secrets.resendApiKey | quote }}
  SENTRY_DSN: {{ .Values.secrets.sentryDsn | quote }}
