apiVersion: stackgres.io/v1
kind: SGCluster
metadata:
  name: trakrf-cluster
  namespace: trakrf-db
spec:
  postgres:
    version: '17'
    extensions:
      - name: timescaledb
  instances: 1
  sgInstanceProfile: trakrf-profile
  pods:
    persistentVolume:
      size: '10Gi'
      storageClass: gp3
  configurations:
    sgPostgresConfig: trakrf-pgconfig
  managedSql:
    scripts:
      - id: 1
        sgScript: trakrf-init
  postgresServices:
    primary:
      type: ClusterIP
    replicas:
      type: ClusterIP
