apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: trakrf-app-wildcard
  namespace: traefik
spec:
  secretName: trakrf-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: trakrf.app
  dnsNames:
    - trakrf.app
    - "*.trakrf.app"
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
